### ISSUE TITLE
Read information from data file

### ISSUE THREAD

**Issue by xplosionmind** [tannerdolby/eleventy-plugin-metagen#23]
Most of us using Eleventy place most—if not all—of the data and metadata concerning our website in the [data folder](https://www.11ty.dev/docs/data-global/ 'Global data - Eleventy Docs'). Specifying the same things within the plugin is quite redundant. Couldn’t the data be passed through the plugin without it being rewritten inside the tag?

**Comment by tannerdolby** [comment]
@xplosionmind Defining site metadata in a global data is definitely one way of doing it. But for specific pages, defining metadata in the templates frontmatter is also very powerful for certain fields that are variable/dynamic and relying on template logic. 

I think I understand what your asking for but its not entirely clear. Can you provide a more reproducible/clear example? 

That being said, the plugin can utilize global data e.g.

```njk
{% metagen 
    title=someDataFile.title or someOtherDataFile.title,
    ...
%}
```

If I understand you correctly, you want the plugin to utilize the metadata from a specific global data file instead of having to manually define each field in a metagen call by providing the global data e.g. `title=someDataFile.title`. So you would want something like this?

```njk
{% metagen "_data/metadata.json" %}

or 

{% metagen "metadata.json" %}
```

or something along those lines? The plugin already supports [shorthand syntax](https://github.com/tannerdolby/eleventy-plugin-metagen#use-your-template-data) for utilizing template data by passing an object to `metagen`, and this works the same for a global data file. It would just have to adhere to the expected field names when defining the global data file in _data.

**Comment by xplosionmind** [comment]
Thanks for your reply, @tannerdolby!

<br>

> you want the plugin to utilize the metadata from a specific global data file instead of having to manually define each field in a metagen call by providing the global data

Exactly!

<br>

> The plugin already supports shorthand syntax for utilizing template data by passing an object to `metagen`

The problem, here, is that both in any page front matter and inside global data I never use `metadata` as a superset. Indeed, e.g. my `title` would be the same as `metadata.title`, and I would be required to uselessly repeat the metadata I want to place within the `metadata` group.

Wouldn’t be possible for metagen to automatically fetch values named with a default name within [Eleventy Data Cascade](https://www.11ty.dev/docs/data-cascade/)?

**Comment by miklb** [comment]
@xplosionmind you can do that now. https://github.com/tannerdolby/eleventy-plugin-metagen/issues/15#issuecomment-999235723
