### ISSUE TITLE
require is not defined (via ReferenceError)

### ISSUE THREAD

**Issue by LorenAmelang** [tannerdolby/eleventy-plugin-metagen#27]
Sorry if this is a hopelessly newbie problem, this is only the second day I've been trying to set up 11ty. 

The main reason for moving my site to 11ty is to fix "Google Zero" and get my site indexed again. They refuse to honor my current canonical tags. 

I followed 
[https://www.npmjs.com/package/eleventy-plugin-metagen](url)

and added
```
	// Canonical - 241124LA
	const metagen = require('eleventy-plugin-metagen');

	module.exports = (eleventyConfig) => {
	    eleventyConfig.addPlugin(metagen);
	};
```
to eleventy.config.js. 

The response is:
```
[11ty] 1. Error in your Eleventy config file 'eleventy.config.js'. (via EleventyConfigError)
[11ty] 2. require is not defined (via ReferenceError)
```
I see
[https://metagendocs.netlify.app/docs/intro/](url)

But it also wants
`const metagen = require('meta-generator');`

What am I not understanding?

**Comment by tannerdolby** [comment]
@LorenAmelang This is simply a module system issue and can be easily fixed. If your `package.json` has `"type": "module"` then 11ty will be expecting ES Modules (ESM) which uses `import` to import resources and `export` to export things. ESM is the new JavaScript standard for handling imports and exports, feel free to read more about CommonJS vs ESM on the 11ty docs: https://www.11ty.dev/docs/cjs-esm/. I will update the metagen docs soon to show examples for ESM usage because currently it's only documenting CommonJS usage.

To solve your issue, you have a few options:

1. Continue to use ESM by keeping `"type": "module"` in the `package.json` and modify your `.eleventy.js` file to conform to ESM.
```js
import metagen from 'eleventy-plugin-metagen';

export default function (eleventyConfig) {
    eleventyConfig.addPlugin(metagen);
};
```
2. Make your 11ty project use CommonJS by removing the `"type": "module"` from your package.json or change the type to `"type": "commonjs"`. This will allow you to use `require` and `module.exports` in the `.eleventy.js` config file like shown in the metagen docs.
```js
const metagen = require('eleventy-plugin-metagen');

module.exports = (eleventyConfig) => {
  eleventyConfig.addPlugin(metagen);
};
```
3. If you would like to keep CommonJS but incrementally use ESM, you can use the `.mjs` extension on JavaScript files where you want to use ESM. For example,`.eleventy.mjs` would use the code shown in option 1.

**Comment by LorenAmelang** [comment]
@tannerdolby 
Wow! Thanks for the quick reply! 

I do have:
/home/loren/11ty_2024/eleventy-base-blog/package.json
```
{
	"name": "eleventy-base-blog",
	"version": "9.0.0",
	"description": "A starter repository for a blog web site using the Eleventy site generator.",
	"type": "module",
	"scripts": {
...
```

I tried 
"modify your .eleventy.js file to conform to ESM."

```
import metagen from 'eleventy-plugin-metagen';

export default function (eleventyConfig) {
    eleventyConfig.addPlugin(metagen);
};
```

```
[loren@Gazp9 eleventy-base-blog]$ npx @11ty/eleventy --serve
[11ty] Eleventy Error (CLI):
[11ty] 1. Error in your Eleventy config file 'eleventy.config.js'. (via EleventyConfigError)
[11ty] 2. Unexpected identifier (via SyntaxError)
[11ty] 
[11ty] Original error stack trace: SyntaxError: Unexpected identifier
[11ty]     at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
[11ty]     at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:299:14)
[11ty]     at async link (node:internal/modules/esm/module_job:67:21)
[loren@Gazp9
```

Made it look like previous import sections there:

```
	// Canonical - 241124LA
	import { metagen } from "eleventy-plugin-metagen";
	export default function (eleventyConfig) { 
		eleventyConfig.addPlugin(metagen);
	};
```

```
[loren@Gazp9 eleventy-base-blog]$ npx @11ty/eleventy --serve
[11ty] Eleventy Error (CLI):
[11ty] 1. Error in your Eleventy config file 'eleventy.config.js'. (via EleventyConfigError)
[11ty] 2. Unexpected token '{' (via SyntaxError)
[11ty] 
[11ty] Original error stack trace: SyntaxError: Unexpected token '{'
[11ty]     at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
[11ty]     at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:299:14)
[11ty]     at async link (node:internal/modules/esm/module_job:67:21)
[loren@Gazp9 eleventy-base-blog]$ 
```
But I'm changing 
/home/loren/11ty_2024/eleventy-base-blog/eleventy.config.js
Which is where the errors are reported...  

not what you said: 
.eleventy.js

There are lots of .eleventy.js files in node_modules - did you maybe mean one of those? 
![eleventyjs](https://github.com/user-attachments/assets/4cc06d7a-d9ba-4a24-9933-d5466e84c1ce)

**Comment by tannerdolby** [comment]
@LorenAmelang You're welcome! I'm happy to help. Do you have a public repository for your 11ty project on GitHub? If so, feel free to drop the repo link in this issue thread and I can submit a PR to resolve things for you if that would be easier.

To hopefully clear things up, the [Eleventy Config](https://www.11ty.dev/docs/config/#default-filenames) file aka `.eleventy.js` or `eleventy.config.js` can be named either way and both are acceptable but you typically only need one config file. If you've decided to use the naming `eleventy.config.js` then this is your 11ty projects config file that you create and modify (usually at the root directory) and it's not a part of `node_modules`.

Your `eleventy.config.js` file should look like this if you want to continue using ESM:

```js
import metagen from 'eleventy-plugin-metagen';

export default function (eleventyConfig) {
    eleventyConfig.addPlugin(metagen);
};
```

Where the first line imports `metagen` as a `default` export without curly braces like shown in the metagen docs because it's not a named export. Modules can only have two flavors of exports, default and named: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#description

I've replicated what we have discussed in a fresh 11ty project and it works as expected.

package.json
```json
{
  "name": "eleventy-sample",
  "version": "1.0.0",
  "description": "",
  "main": "eleventy.config.js",
  "type": "module",
  "scripts": {
    "build": "npx @11ty/eleventy",
    "dev": "npx @11ty/eleventy --serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@11ty/eleventy": "^3.0.0",
    "eleventy-plugin-metagen": "^1.8.3"
  }
}
```

eleventy.config.js
```js
import metagen from 'eleventy-plugin-metagen';

export default function (eleventyConfig) {
    eleventyConfig.addPlugin(metagen);
};
```

index.njk
```nunjucks
<!DOCTYPE html>
<html lang="en">
<head>
    {% metagen
        title="foo bar"
    %}
</head>
<body>
    <h1>Test</h1>
</body>
</html>
```

<img width="662" alt="Screen Shot 2024-11-25 at 9 39 10 PM" src="https://github.com/user-attachments/assets/b539c6a5-8b2d-4760-9f44-a53f668126cf">
<img width="666" alt="Screen Shot 2024-11-25 at 9 43 55 PM" src="https://github.com/user-attachments/assets/32e0ffd4-1b0e-440e-870c-c50ab1fb7c0d">
<img width="1277" alt="Screen Shot 2024-11-25 at 9 39 51 PM" src="https://github.com/user-attachments/assets/0324caad-656d-4e2b-8d73-45c13b0aa303">

**Comment by LorenAmelang** [comment]
@tannerdolby Thanks for following up! As far as I can see I've matched your suggestions, but get the same error. 

`Do you have a public repository for your 11ty project on GitHub? If so, feel free to drop the repo link in this issue thread and I can submit a PR to resolve things for you if that would be easier.`

Not on GitHub. Guess I could put it there if that's way better for you. 

I just put the current experimental site at: 
https://www.psychoros.com/11/index.html

The internal links jump out to the old Gridsome site - is there a simple way to move all of them to the test URL without editing all the sources? 

And that is the version that built, before I edited in the metagen import. 


I don't have anything like your index.njk...  
Mine looks like this:

```
---js
const eleventyNavigation = {
	key: "Home",
	order: 1
};

const numberOfLatestPostsToShow = 16;
---
{% set postsCount = collections.posts | length %}
{% set latestPostsCount = postsCount | min(numberOfLatestPostsToShow) %}
<h1>Latest {{ latestPostsCount }} Post{% if latestPostsCount != 1 %}s{% endif %}</h1>

{% set postslist = collections.posts | head(-1 * numberOfLatestPostsToShow) %}
{% set postslistCounter = postsCount %}
{% include "postslist.njk" %}

{% set morePosts = postsCount - numberOfLatestPostsToShow %}
{% if morePosts > 0 %}
<p>{{ morePosts }} more post{% if morePosts != 1 %}s{% endif %} can be found in <a href="blog.njk">the archive</a>.</p>
{% endif %}
{# List every content page in the project #}
{#
<ul>
	{%- for entry in collections.all %}
	<li><a href="{{ entry.url }}"><code>{{ entry.url }}</code></a></li>
	{%- endfor %}
</ul>
#}
```
Can I add head and body sections to that? Or is your index.njk the equivalent to my index.html files for each post? 

Maybe I need to move my posts from .md to .njk? But if I could just put a canonical line in the head of each post with .njk, do I need metagen? 

Sorry to be so ignorant! 

Loren

**Comment by tannerdolby** [comment]
@LorenAmelang No problem! I'm confident we will get this sorted out for you. There is a lot to unpack since I'm not sure what your project structure looks like and if you're using layouts or not. If you are able to put your code in a public repository on GitHub, it will be much easier for me to help resolve the issues you're having.

The `metagen` shortcode can be used in Nunjucks templates or Markdown files and works in a CommonJS or ESM setup. You most likely have another error/issue going on. To best utilize `metagen` in a dynamic pattern, you will typically want to define metadata for specific pages in frontmatter or global data files and when pages are rendered by some base layout, then utilize `metagen` to generate document metadata for the page.

For example, on my website the [`post.njk`](https://github.com/tannerdolby/tannerdolby.com/blob/master/src/_includes/layouts/post.njk) layout renders the blog post content from the Markdown files in the [`writing`](https://github.com/tannerdolby/tannerdolby.com/tree/master/src/writing) folder and then the post layout uses the [`base.njk`](https://github.com/tannerdolby/tannerdolby.com/blob/master/src/_includes/layouts/base.njk) layout which is where the document metadata is generated via the `metagen` shortcode that generates a canonical link along with other useful metadata.

<img width="1185" alt="Screen Shot 2024-11-26 at 4 10 44 PM" src="https://github.com/user-attachments/assets/81f4e158-7830-49a8-b1d4-bd45093090df">



------

> The internal links jump out to the old Gridsome site - is there a simple way to move all of them to the test URL without editing all the sources?

If you're proxying/rewriting to a different site e.g. the old Gridsome site then you will have to update the sources in your code or hosting service to reflect the expected destination.

Since I've included working examples for the most basic usage of `metagen` in templates for both CommonJS and ESM projects. I think the only way for me to fully understand the problems you're having is to see your projects code and start debugging from there.

**Comment by LorenAmelang** [comment]
@tannerdolby 
I just created 
[https://github.com/LorenAmelang/11tyTest](https://github.com/LorenAmelang/11tyTest)

Except, as the ReadMe says, for the huge node_modules folder. Seems there should be some way to copy it directly from 
[https://github.com/11ty/eleventy-base-blog.git](https://github.com/11ty/eleventy-base-blog.git)
and 
[https://www.npmjs.com/package/eleventy-plugin-metagen](https://www.npmjs.com/package/eleventy-plugin-metagen)
without crossing my slow internet...

Is this anywhere close to useful for you? What do I need to add?

**Comment by tannerdolby** [comment]
@LorenAmelang I only see a README and LICENSE added to your 11tyTest repository. Can you commit all of your source code? It seems like you are wanting to use the [`eleventy-base-blog`](https://github.com/11ty/eleventy-base-blog/tree/main) so you can click the ["Use this template"](https://github.com/new?template_name=eleventy-base-blog&template_owner=11ty) button in the top right corner of the repository on GitHub to create a new repo with the eleventy-base-blog template code or if you've already copied the code from there and started working locally, just simply commit the rest of your code to the existing 11tyTest repository.

It's best practice to never commit `node_modules` to version control by ensuring it's being ignored in your [`.gitignore`](https://github.com/tannerdolby/eleventy-plugin-metagen/blob/master/.gitignore). The `package.json` is all that's needed for developers to install your projects dependencies because running `npm install` generates a `package-lock.json` and `node_modules` folder.

Once the 11tyTest repo or a new repo that you create from the eleventy-base-blog template has all of your code in it and shows a reproducible example of the errors, I can fork your repo and start debugging then submit a PR to fix the issues.

**Comment by LorenAmelang** [comment]
@tannerdolby 

I think maybe my uploaded files were saved this time: 

[https://github.com/LorenAmelang/11ty-base-blog/tree/LorenAmelang-add-1](https://github.com/LorenAmelang/11ty-base-blog/tree/LorenAmelang-add-1)

This time I tried adding a new fork instead of adding the files to the original base level. 

Sorry, I've only ever used GitHub to download things...  Let me know if this works. Feel free to fix it if you can.

**Comment by tannerdolby** [comment]
@LorenAmelang No worries on being new to GitHub! I was in the same boat once upon a time as well. Thank you for uploading the source code. I checked out the `LorenAmelang-add-1` branch and was able to find and resolve the issues. Now I'm able to run your site locally with metagen generating document metadata from the base layout for all pages.

<img width="582" alt="Screen Shot 2024-11-27 at 10 40 20 PM" src="https://github.com/user-attachments/assets/61e60adf-5b51-4d21-a550-81a2b99151dc">

------------------

It looks like the permissions you've set on the repository aren't allowing public contributions so my permission was denied when attempting to push up my changes for a pull request. (This was actually my fault for not forking your repo and pushing my changes to my own repo then creating a PR in the remote)

<img width="723" alt="Screen Shot 2024-11-27 at 10 31 18 PM" src="https://github.com/user-attachments/assets/2e9e9253-fee0-4d4d-9d6f-c2cdea25aec2">

--------------------

I'll just include the changes below and you can copy/paste them into your project locally. The code on [L93-98](https://github.com/LorenAmelang/11ty-base-blog/blob/LorenAmelang-add-1/eleventy.config.js#L93-L98) in `eleventy.config.js` caused the build-time errors since imports can't be used inside functions and there was also a duplicate default export which caused the unexpected identifiers. After fixing the structure of that file there aren't anymore errors when building or serving the site. Just replace your existing files with the contents below then you should be able to run `npm run build` and `npm run start` without issues 🎈 

eleventy.config.js
```js
import { IdAttributePlugin, InputPathToUrlTransformPlugin, HtmlBasePlugin } from "@11ty/eleventy";
import { feedPlugin } from "@11ty/eleventy-plugin-rss";
import pluginSyntaxHighlight from "@11ty/eleventy-plugin-syntaxhighlight";
import pluginNavigation from "@11ty/eleventy-navigation";
import { eleventyImageTransformPlugin } from "@11ty/eleventy-img";
// Canonical - 241124LA
import metagen from 'eleventy-plugin-metagen';

import pluginFilters from "./_config/filters.js";

/** @param {import("@11ty/eleventy").UserConfig} eleventyConfig */
export default async function (eleventyConfig) {
    // Drafts, see also _data/eleventyDataSchema.js
    eleventyConfig.addPreprocessor("drafts", "*", (data, content) => {
        if (data.draft && process.env.ELEVENTY_RUN_MODE === "build") {
            return false;
        }
    });

    // Copy the contents of the `public` folder to the output folder
    // For example, `./public/css/` ends up in `_site/css/`
    eleventyConfig
        .addPassthroughCopy({
            "./public/": "/"
        })
        .addPassthroughCopy("./content/feed/pretty-atom-feed.xsl");

    // Run Eleventy when these files change:
    // https://www.11ty.dev/docs/watch-serve/#add-your-own-watch-targets

    // Watch content images for the image pipeline.
    eleventyConfig.addWatchTarget("content/**/*.{svg,webp,png,jpeg}");

    // Per-page bundles, see https://github.com/11ty/eleventy-plugin-bundle
    // Adds the {% css %} paired shortcode
    eleventyConfig.addBundle("css", {
        toFileDirectory: "dist",
    });
    // Adds the {% js %} paired shortcode
    eleventyConfig.addBundle("js", {
        toFileDirectory: "dist",
    });

    // Meta Generator
    eleventyConfig.addPlugin(metagen);

    // Filters
    eleventyConfig.addPlugin(pluginFilters);

    eleventyConfig.addPlugin(IdAttributePlugin, {
        // by default we use Eleventy’s built-in `slugify` filter:
        // slugify: eleventyConfig.getFilter("slugify"),
        // selector: "h1,h2,h3,h4,h5,h6", // default
    });

    // Official plugins
    eleventyConfig.addPlugin(pluginSyntaxHighlight, {
        preAttributes: { tabindex: 0 }
    });
    eleventyConfig.addPlugin(pluginNavigation);
    eleventyConfig.addPlugin(HtmlBasePlugin);
    eleventyConfig.addPlugin(InputPathToUrlTransformPlugin);

    eleventyConfig.addPlugin(feedPlugin, {
        type: "atom", // or "rss", "json"
        outputPath: "/feed/feed.xml",
        stylesheet: "pretty-atom-feed.xsl",
        templateData: {
            eleventyNavigation: {
                key: "Feed",
                order: 4
            }
        },
        collection: {
            name: "posts",
            limit: 10,
        },
        metadata: {
            language: "en",
            title: "Blog Title",
            subtitle: "This is a longer description about your blog.",
            base: "https://example.com/",
            author: {
                name: "Your Name"
            }
        }
    });

    // Image optimization: https://www.11ty.dev/docs/plugins/image/#eleventy-transform
    eleventyConfig.addPlugin(eleventyImageTransformPlugin, {
        // File extensions to process in _site folder
        extensions: "html",

        // Output formats for each image.
        formats: ["avif", "webp", "auto"],

        // widths: ["auto"],

        defaultAttributes: {
            // e.g. <img loading decoding> assigned on the HTML tag will override these values.
            loading: "lazy",
            decoding: "async",
        }
    });

    // Features to make your build faster (when you need them)

    // If your passthrough copy gets heavy and cumbersome, add this line
    // to emulate the file copy on the dev server. Learn more:
    // https://www.11ty.dev/docs/copy/#emulate-passthrough-copy-during-serve

    // eleventyConfig.setServerPassthroughCopyBehavior("passthrough");

    eleventyConfig.addShortcode("currentBuildDate", () => {
        return (new Date()).toISOString();
    });
};

export const config = {
    // Control which files Eleventy will process
    // e.g.: *.md, *.njk, *.html, *.liquid
    templateFormats: [
        "md",
        "njk",
        "html",
        "liquid",
        "11ty.js",
    ],

    // Pre-process *.md files with: (default: `liquid`)
    markdownTemplateEngine: "njk",

    // Pre-process *.html files with: (default: `liquid`)
    htmlTemplateEngine: "njk",

    // These are all optional:
    dir: {
        input: "content",          // default: "."
        includes: "../_includes",  // default: "_includes" (`input` relative)
        data: "../_data",          // default: "_data" (`input` relative)
        output: "_site"
    },

    // -----------------------------------------------------------------
    // Optional items:
    // -----------------------------------------------------------------

    // If your site deploys to a subdirectory, change `pathPrefix`.
    // Read more: https://www.11ty.dev/docs/config/#deploy-to-a-subdirectory-with-a-path-prefix

    // When paired with the HTML <base> plugin https://www.11ty.dev/docs/plugins/html-base/
    // it will transform any absolute URLs in your HTML to include this
    // folder name and does **not** affect where things go in the output folder.

    // pathPrefix: "/",
};
```

_inclues/layouts/base.njk
```html
<!doctype html>
<html lang="{{ metadata.language }}">
	<head>
		<!-- TODO: Replace img and img_ alt with the social share image and alt text of your choice -->
		{% metagen
            title=title or metadata.title,
            desc=description or metadata.description,
            url=metadata.url + page.url,
            img="https://i.imgur.com/0ogkTp7_d.webp?maxwidth=760&fidelity=grand",
            img_alt="Temporary cat photo",
            name=metadata.author.name,
            generator=metadata.generator,
            comments=true
        %}
		<link rel="alternate" href="feed/feed.xml" type="application/atom+xml" title="{{ metadata.title }}">

		{#- Uncomment this if you’d like folks to know that you used Eleventy to build your site!  #}
		{#- <meta name="generator" content="{{ eleventy.generator }}"> #}

		{#-
		Plain-text bundles are provided via the `eleventy-plugin-bundle` plugin:
		1. CSS:
			* Add to a per-page bundle using `{% css %}{% endcss %}`
			* Retrieve bundle content using `{% getBundle "css" %}` or `{% getBundleFileUrl "css" %}`
		2. Or for JavaScript:
			* Add to a per-page bundle using `{% js %}{% endjs %}`
			* Retrieve via `{% getBundle "js" %}` or `{% getBundleFileUrl "js" %}`
		3. Learn more: https://github.com/11ty/eleventy-plugin-bundle
		#}

		{#- Add an arbitrary string to the bundle #}
		{%- css %}/* This is an arbitrary CSS string added to the bundle */{% endcss %}
		{#- Add the contents of a file to the bundle #}
		{%- css %}{% include "public/css/index.css" %}{% endcss %}
		{#- Or you can add from node_modules #}
		{# {%- css %}{% include "node_modules/prismjs/themes/prism-okaidia.css" %}{% endcss %} #}

		{#- Render the CSS bundle using inlined CSS (for the fastest site performance in production) #}
		<style>{% getBundle "css" %}</style>
		{#- Renders the CSS bundle using a separate file, if you can't set CSP directive style-src: 'unsafe-inline' #}
		{#- <link rel="stylesheet" href="{% getBundleFileUrl "css" %}"> #}

		{#- Add the heading-anchors web component to the JavaScript bundle #}
		{%- js %}{% include "node_modules/@zachleat/heading-anchors/heading-anchors.js" %}{% endjs %}
	</head>
	<body>
		<a href="#skip" class="visually-hidden">Skip to main content</a>

		<header>
			<a href="/" class="home-link">{{ metadata.title }}</a>

			{#- Read more about `eleventy-navigation` at https://www.11ty.dev/docs/plugins/navigation/ #}
			<nav>
				<h2 class="visually-hidden">Top level navigation menu</h2>
				<ul class="nav">
				{%- for entry in collections.all | eleventyNavigation %}
					<li class="nav-item"><a href="{{ entry.url }}"{% if entry.url == page.url %} aria-current="page"{% endif %}>{{ entry.title }}</a></li>
				{%- endfor %}
				</ul>
			</nav>
		</header>

		<main id="skip">
			<heading-anchors>
				{{ content | safe }}
			</heading-anchors>
		</main>

		<footer>
			<p><em>Built with <a href="https://www.11ty.dev/">{{ eleventy.generator }}</a></em></p>
		</footer>

		<!-- This page `{{ page.url }}` was built on {% currentBuildDate %} -->
		<script type="module" src="{% getBundleFileUrl "js" %}"></script>
	</body>
</html>

```

_data/metadata.js
```js
export default {
    title: "Psychoros",
    url: "https://www.psychoros.com",
    language: "en",
    generator: 'eleventy',
    description: "I am writing about my experiences as a naval navel-gazer.",
    author: {
        name: "Loren Amelang",
        email: "youremailaddress@example.com",
        url: "https://www.psychoros.com/about"
    }
}
```

**Comment by LorenAmelang** [comment]
@tannerdolby 

Maybe not necessary, I'll try to fix my local file with your clues. But I just searched up how to add you to the "public" repo, and it says you've been invited. Would be nice to know if that works now...  

[https://stackoverflow.com/questions/17442930/can-anybody-push-to-my-project-on-github](https://stackoverflow.com/questions/17442930/can-anybody-push-to-my-project-on-github)

If you want to grant someone else privileges to push to your repo, you would need to configure that access in the project settings.

To contribute to projects in which you don't have push access, you push to your own copy of the repo, then ask for a pull-request. Linux is not a good example for that, because the kernel developers do not use GitHub pull requests.

That's the "Settings" item at the right end of the "Code, Issues..." header. 

Off to edit files...  Appreciate your help!

**Comment by LorenAmelang** [comment]
@tannerdolby 

Wow! That works! I can move on to customizing everything...  

Looking at the new head section, I see `<!-- Twitter -->`...  Does that only get used if I intentionally post a link to the page on Twitter? (I left Twitter permanently when they blocked the Twitterrific app and forced everyone into the algorithm.) 

And `<!-- Open Graph -->`...  Who all can see that? Any chance of my Mastodon instance using it? Maybe I need to replace the "Temporary cat photo"?

`<meta property="og:image" content="https://i.imgur.com/0ogkTp7_d.webp?maxwidth=760&amp;fidelity=grand"> `
Shows "image does not exist" and "no alt attribute"...  

But I now have what I wanted - a proper-looking canonical tag inside head: 
`<link rel="canonical" href="https://www.psychoros.com/blog/my-origin/">`

One more question you might have a clue about...  I'm hosting the new site as 
http://www.psychoros.com/11/
while I work on it, so the old 
http://www.psychoros.com/
site stays accessible. Is there a quick way to change all the canonical tags to /11/ for now, and back to the main URL once I'm ready to go public? 

Otherwise I guess I could manually edit a few pages to use in Google Search Console, to see if they actually see what looks to me like a proper canonical tag...

Thank You!

**Comment by tannerdolby** [comment]
> To contribute to projects in which you don't have push access, you push to your own copy of the repo, then ask for a pull-request. Linux is not a good example for that, because the kernel developers do not use GitHub pull requests.

@LorenAmelang You're welcome! I'm glad I was able to help. And thank you for the refresher on OSS contributions! I've been contributing mostly to projects I'm a part of this year and totally forgot to first clone your project and then clone my fork, instead of directly cloning your project (which this is what you do if your a member of that project/org).

What you mentioned from that StackOverflow answer is totally correct, I forgot to fork your repo first before cloning and mistakingly cloned your remote repo instead of my own fork so that's why I saw the permissions issue as expected 😅 In the future if you have any issues with that repo I'll make sure to fork it and then clone my fork to contribute PRs if needed. I saw your collaboration invite but I'll let it expire as I don't need that access to contribute.

> Wow! That works! I can move on to customizing everything... Looking at the new head section, I see `<!-- Twitter -->`... Does that only get used if I intentionally post a link to the page on Twitter? (I left Twitter permanently when they blocked the Twitterrific app and forced everyone into the algorithm.) And `<!-- Open Graph -->`... Who all can see that? Any chance of my Mastodon instance using it? Maybe I need to replace the "Temporary cat photo"?

Awesome! Glad to hear the errors are resolved. The ` <!-- Twitter -->` and `<!-- Open graph -->` lines are just HTML comments in the `<head>` to separate the two social share metadata sections (Twitter and Open Graph) and the comments can be turned off by setting `comments=false` when using `metagen` or simply omitting the `comments` field when using the shortcode. Anyone who views the source of the HTML page can see HTML comments but they are purely cosmetic. Yes, the Twitter meta tags are specifically for displaying a social share card for links to your website that appear on Twitter/X and the Open Graph Protocol is used by Mastadon along with other sites to display social share cards.

The `metagen` shortcode generates metadata for both Twitter and Open Graph metadata to ensure your site has social share functionality across the different social media sites. Yes, you will want to replace the `img` and `img_alt` arguments with a social share image of your choosing, I just added a random cat photo from imgur as a placeholder for you.

> Is there a quick way to change all the canonical tags to /11/ for now, and back to the main URL once I'm ready to go public?

Yes, you can simply tell `metagen` whatever URL you want to use and it will generate the canonical tag with what you tell it.  Since your sites base URL is being defined in `_data/metadata.js`, simply change `url: "https://www.psychoros.com",` to `url: "https://www.psychoros.com/11",` or you could temporarily append `/11` in the metagen shortcode e.g. `url=metadata.url + "/11" + page.url,`. Then whenever you're ready to go public just ensure the URL is set the way you want it without the `/11` in the path.

**Comment by tannerdolby** [comment]
@LorenAmelang Closing this issue as we have resolved the problem you were having directly relating to using `metagen` in an ESM context. I'm happy to answer any additional questions you might have in this thread if needed. Thank you for working with me to get this resolved!
