### ISSUE TITLE
Template variables are working

### ISSUE THREAD

**Issue by JbIPS** [tannerdolby/eleventy-plugin-metagen#5]
I saw in your README that template variables are not supposed to work.

Out of curiosity, I tried this:
```
{% metagen
    title=title or metadata.title,
    desc=description or metadata.description,
    url="https://cameo.fr/" + page.url,
    img="https://jbips.github.io/landing/img/banner.png",
    img_alt="Logo Cameo",
    twitterHandle="@CameoTalents",
    name="Cameo"
%}
```
and this work perfectly!

Should I remove this paragraph on the README and replace it with an example of using variable or were you thinking of another issue?

**Comment by tannerdolby** [comment]
Thanks for pointing this out @JbIPS !

Your right! It seems to work without embedding the template variables in double curly braces like we would do in a liquid/nunjucks template ie `{{ metadata.title }}`. Using the curly braces to pull in template variables doesn't work and that's why I originally came to the conclusion that template variables couldn't be properly handled.

After testing this from the example you showed above, I completely agree, it does work perfectly with template variables as long as they aren't wrapped in double curly braces, like `metadata.title`. If you would like to update the README and provide an example that uses template variables I'm happy to review it and merge into `master`.
